/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface CoachingComment {
  text: string;
  category: 'brilliant' | 'best' | 'inaccuracy' | 'mistake' | 'blunder' | 'general';
}

export const COACHING_COMMENTS: CoachingComment[] = [
  // BRILLIANT (40)
  { text: "Incredible vision! That move sets up a winning sequence several steps ahead.", category: 'brilliant' },
  { text: "Pure genius. You've completely paralyzed your opponent's strategy.", category: 'brilliant' },
  { text: "That was a masterclass in positional pressure. Excellent find!", category: 'brilliant' },
  { text: "A move of grandmaster quality. The engine is impressed!", category: 'brilliant' },
  { text: "You just found the only winning resource in this complex position.", category: 'brilliant' },
  { text: "Spectacular! That column placement creates an unstoppable fork.", category: 'brilliant' },
  { text: "I didn't even see that coming. Your tactical awareness is peaking!", category: 'brilliant' },
  { text: "Utterly brilliant. You've turned a drawish position into a win.", category: 'brilliant' },
  { text: "That's the kind of move they'll analyze in textbooks. Bravo!", category: 'brilliant' },
  { text: "You've correctly identified the critical square. Clinical finish.", category: 'brilliant' },
  { text: "Magnificent. You're thinking like a neural network right now.", category: 'brilliant' },
  { text: "That move is a total game-changer. Total dominance.", category: 'brilliant' },
  { text: "Elegance meets efficiency. You've solved the puzzle.", category: 'brilliant' },
  { text: "A brilliant trap! Your opponent is walking right into it.", category: 'brilliant' },
  { text: "Exceptional depth. You're seeing patterns others miss.", category: 'brilliant' },
  { text: "That was a bold sacrifice that paid off perfectly. Risk handled well.", category: 'brilliant' },
  { text: "High-level strategy. You're controlling the flow of the game.", category: 'brilliant' },
  { text: "That move is a signature of a seasoned pro. Keep it up!", category: 'brilliant' },
  { text: "Absolute tactical masterstroke. The board is yours.", category: 'brilliant' },
  { text: "A move that defines the match. You've seized the initiative.", category: 'brilliant' },
  { text: "You've woven a beautiful web. There's no escape now.", category: 'brilliant' },
  { text: "That was a stroke of strategic lightning! Powerful.", category: 'brilliant' },
  { text: "You're playing a different game than your opponent. Level: Elite.", category: 'brilliant' },
  { text: "That placement is mathematically perfect. Logic prevails.", category: 'brilliant' },
  { text: "Brilliant defense turned into a crushing counter-attack.", category: 'brilliant' },
  { text: "You've mastered the spatial dynamics of the grid.", category: 'brilliant' },
  { text: "That move shows immense patience and calculated aggression.", category: 'brilliant' },
  { text: "A visionary play. You're looking 10 moves ahead.", category: 'brilliant' },
  { text: "I'm literally speechless. That was the perfect play.", category: 'brilliant' },
  { text: "You've just rewritten the strategy for this opening. Innovative!", category: 'brilliant' },
  { text: "That was a 'Holy Grail' move. Extremely rare find.", category: 'brilliant' },
  { text: "You're making the AI look like a novice. Sharp!", category: 'brilliant' },
  { text: "Precision under pressure. You've earned that gold star.", category: 'brilliant' },
  { text: "Strategic poetry. The way you link your pieces is art.", category: 'brilliant' },
  { text: "That was a high-frequency tactical strike. Boom!", category: 'brilliant' },
  { text: "You've identified the weakness in the opponent's center. Exploited beautifully.", category: 'brilliant' },
  { text: "A move of pure clarity. You see the board for what it is.", category: 'brilliant' },
  { text: "That was a tactical symphony. Every piece is in perfect harmony.", category: 'brilliant' },
  { text: "Calculated to the last bit. Your brain is a supercomputer.", category: 'brilliant' },
  { text: "Total control. You've earned the title of Grid Architect.", category: 'brilliant' },

  // BEST (40)
  { text: "Solid play. That was the most logical move in this position.", category: 'best' },
  { text: "Good find! You're keeping the pressure on the opponent.", category: 'best' },
  { text: "Exactly what the engine recommended. Consistent and strong.", category: 'best' },
  { text: "Excellent choice. You're building a very stable position.", category: 'best' },
  { text: "That was the most efficient way to advance your position.", category: 'best' },
  { text: "Great placement. You're controlling the key central columns.", category: 'best' },
  { text: "Nicely done. You've successfully neutralized the threat.", category: 'best' },
  { text: "A very strong move that maintains your advantage.", category: 'best' },
  { text: "You're playing very accurately. Keep this momentum!", category: 'best' },
  { text: "Good strategic sense. This builds towards a long-term win.", category: 'best' },
  { text: "Precisely the right response. You're not easily rattled.", category: 'best' },
  { text: "A high-quality move. You're making the right trades.", category: 'best' },
  { text: "Very logical. You're prioritizing the right threats.", category: 'best' },
  { text: "That move tightens the noose. Your opponent is feeling it.", category: 'best' },
  { text: "Clean and effective. You're sticking to the fundamentals.", category: 'best' },
  { text: "Excellent depth of calculation. You're safe here.", category: 'best' },
  { text: "Good vision. You've spotted the best resource available.", category: 'best' },
  { text: "A very professional move. This is how games are won.", category: 'best' },
  { text: "Nice find. You're maximizing your piece utility.", category: 'best' },
  { text: "That move shows great maturity. Avoiding unnecessary risks.", category: 'best' },
  { text: "Strong and steady. You're winning the war of attrition.", category: 'best' },
  { text: "Exactly the right timing. You've seized the moment.", category: 'best' },
  { text: "Good positional understanding. The grid looks solid.", category: 'best' },
  { text: "Very accurate play. You're giving nothing away.", category: 'best' },
  { text: "Excellent adjustment. You've adapted to the shift in play.", category: 'best' },
  { text: "Sharp play! You're punishing the opponent's sub-optimal moves.", category: 'best' },
  { text: "Good focus. You're concentrating on the win condition.", category: 'best' },
  { text: "A very effective block. You've forced them to rethink.", category: 'best' },
  { text: "Nicely spotted! That diagonal was looking dangerous.", category: 'best' },
  { text: "Very sensible. You're developing your pieces naturally.", category: 'best' },
  { text: "Good balance of offense and defense. Very well-rounded.", category: 'best' },
  { text: "Precise execution. You're following through on your plan.", category: 'best' },
  { text: "Great awareness. You've correctly valued the center.", category: 'best' },
  { text: "A solid brick in your defensive wall. Hard to break through.", category: 'best' },
  { text: "Nicely played. You're keeping your options open.", category: 'best' },
  { text: "Good pressure. You're making it hard for them to breathe.", category: 'best' },
  { text: "Very disciplined move. You're playing like a grandmaster apprentice.", category: 'best' },
  { text: "Excellent! That move secures your lead.", category: 'best' },
  { text: "Good strategic footing. You're ready for any response.", category: 'best' },
  { text: "That move is a safe bet, and the best one here.", category: 'best' },

  // INACCURACY (40)
  { text: "A bit slow. There were sharper ways to handle this.", category: 'inaccuracy' },
  { text: "Not quite the best. You've allowed a bit of counter-play.", category: 'inaccuracy' },
  { text: "A slightly passive move. You could have been more aggressive.", category: 'inaccuracy' },
  { text: "You missed a slightly better placement in the center.", category: 'inaccuracy' },
  { text: "A bit of a missed opportunity to transition into a winning endgame.", category: 'inaccuracy' },
  { text: "That move is okay, but it doesn't really challenge the opponent.", category: 'inaccuracy' },
  { text: "Slightly sub-optimal. You've given up a tiny bit of your edge.", category: 'inaccuracy' },
  { text: "You're a bit too focused on one side of the board. Look wider.", category: 'inaccuracy' },
  { text: "A bit of a hesitation move. Trust your first instinct next time.", category: 'inaccuracy' },
  { text: "Not the most principled move. You've deviated from the ideal line.", category: 'inaccuracy' },
  { text: "A bit reactive. Try to look for pro-active resources.", category: 'inaccuracy' },
  { text: "Slightly misplaced piece. It's not as influential as it could be.", category: 'inaccuracy' },
  { text: "You've missed a minor tactical nuance here. Still safe though.", category: 'inaccuracy' },
  { text: "A bit predictable. Try to mask your intentions more.", category: 'inaccuracy' },
  { text: "Slightly inefficient. You're taking an extra step to win.", category: 'inaccuracy' },
  { text: "A bit of a 'wait-and-see' move. Don't let them dictate the pace.", category: 'inaccuracy' },
  { text: "Not the cleanest win path. There were simpler options.", category: 'inaccuracy' },
  { text: "A bit too safe. You had a chance to go for the throat.", category: 'inaccuracy' },
  { text: "Slightly cluttered your own diagonal. Watch your spacing.", category: 'inaccuracy' },
  { text: "A bit of a redundant move. That column was already secure.", category: 'inaccuracy' },
  { text: "Not the most ambitious play. Aim higher!", category: 'inaccuracy' },
  { text: "A bit of a lukewarm response. Bring more heat next turn.", category: 'inaccuracy' },
  { text: "Slightly ignored the developing threat on the left.", category: 'inaccuracy' },
  { text: "A bit too focused on the bottom rows. The top is open too.", category: 'inaccuracy' },
  { text: "Not quite punishing enough. You let them off the hook slightly.", category: 'inaccuracy' },
  { text: "A bit of a defensive lapse. They might find a way in.", category: 'inaccuracy' },
  { text: "Slightly out of sync with your overall strategy.", category: 'inaccuracy' },
  { text: "A bit of a missed tempo. You could have forced an error.", category: 'inaccuracy' },
  { text: "Not the highest-probability play. Rely on more stable lines.", category: 'inaccuracy' },
  { text: "A bit of a tactical 'flicker'. Stay steady.", category: 'inaccuracy' },
  { text: "Slightly better moves were available if you looked 2 moves deeper.", category: 'inaccuracy' },
  { text: "A bit too optimistic. The defense was stronger than you thought.", category: 'inaccuracy' },
  { text: "Not the most creative solve. There was a prettier move.", category: 'inaccuracy' },
  { text: "A bit of a standard response to a non-standard problem.", category: 'inaccuracy' },
  { text: "Slightly misjudged the central value here.", category: 'inaccuracy' },
  { text: "A bit of a lapse in concentration? Focus on every piece.", category: 'inaccuracy' },
  { text: "Not quite the masterstroke we expected. You're getting there.", category: 'inaccuracy' },
  { text: "A bit of a 'safety first' play when a win was near.", category: 'inaccuracy' },
  { text: "Slightly too attached to your current formation.", category: 'inaccuracy' },
  { text: "A bit of a minor slip. Nothing fatal, but be careful.", category: 'inaccuracy' },

  // MISTAKE (40)
  { text: "That was a mistake. You've handed the initiative to your opponent.", category: 'mistake' },
  { text: "Careful! That move ignores a serious developing threat.", category: 'mistake' },
  { text: "You just let a winning advantage slip away. Focus!", category: 'mistake' },
  { text: "A significant error. You've allowed a double threat to form.", category: 'mistake' },
  { text: "Poor choice. You're blocking your own best winning line.", category: 'mistake' },
  { text: "That was a tactical oversight. Your defense is now compromised.", category: 'mistake' },
  { text: "You've completely missed the opponent's counter-attack. Look closer.", category: 'mistake' },
  { text: "A bad trade. You've given up more than you gained.", category: 'mistake' },
  { text: "You're playing a bit recklessly. Slow down and calculate.", category: 'mistake' },
  { text: "That move creates a massive hole in your center. Fix it fast!", category: 'mistake' },
  { text: "You've fallen for a simple trap. Don't bite so easily.", category: 'mistake' },
  { text: "A strategic blunder. You've lost control of the board.", category: 'mistake' },
  { text: "Very sloppy work. You're gifting them the win.", category: 'mistake' },
  { text: "That move is a waste of a turn. It does nothing to help.", category: 'mistake' },
  { text: "You've miscalculated the endgame. This could cost you.", category: 'mistake' },
  { text: "A total lack of awareness. The winning move was right there!", category: 'mistake' },
  { text: "You're playing into their hands. Stop being so predictable.", category: 'mistake' },
  { text: "That placement is disastrous. It opens up multiple lines for them.", category: 'mistake' },
  { text: "You've ignored the principles of the grid. Chaos follows.", category: 'mistake' },
  { text: "A very poor tactical evaluation. You're in trouble now.", category: 'mistake' },
  { text: "You just gave them a free win resource. Wake up!", category: 'mistake' },
  { text: "That move is completely unprincipled. It makes no sense.", category: 'mistake' },
  { text: "You've allowed them to build a winning fork. Fatal mistake.", category: 'mistake' },
  { text: "A terrible misjudgment of the position's tension.", category: 'mistake' },
  { text: "You're playing too defensively when you should be attacking.", category: 'mistake' },
  { text: "That move completely undermines your previous hard work.", category: 'mistake' },
  { text: "A glaring hole in your logic. The AI is already laughing.", category: 'mistake' },
  { text: "You've abandoned the center. That's a huge mistake.", category: 'mistake' },
  { text: "Terrible timing. You've struck too late or too early.", category: 'mistake' },
  { text: "You're being far too passive. Attack or perish!", category: 'mistake' },
  { text: "That move is a tactical nightmare. Good luck recovering.", category: 'mistake' },
  { text: "You've lost your nerve. Stay strong or you'll lose.", category: 'mistake' },
  { text: "A complete strategic collapse. You needs to rebuild.", category: 'mistake' },
  { text: "You've missed a point-blank win. How is that possible?", category: 'mistake' },
  { text: "That move is a total gift to the opponent. Merry Christmas?", category: 'mistake' },
  { text: "You're ignoring the basic math of the diagonals.", category: 'mistake' },
  { text: "A huge lapse in judgment. This is a turning point for them.", category: 'mistake' },
  { text: "You've sabotaged your own winning sequence. Brilliant... for them.", category: 'mistake' },
  { text: "That move is a total disaster. Restarting might be easier.", category: 'mistake' },
  { text: "You've lost the thread. You're just placing pieces blindly.", category: 'mistake' },

  // BLUNDER (40)
  { text: "TOTAL DISASTER. You've literally handed them the win on a silver platter.", category: 'blunder' },
  { text: "Game over. That move was a complete and utter blunder.", category: 'blunder' },
  { text: "I can't believe my sensors. You've allowed a 4-in-a-row in plain sight!", category: 'blunder' },
  { text: "Absolute catastrophe. Your position has completely imploded.", category: 'blunder' },
  { text: "You've just committed tactical suicide. There's no coming back.", category: 'blunder' },
  { text: "A blunder of epic proportions. The engine is crying.", category: 'blunder' },
  { text: "You've ignored a 1-move win. THE ONE MOVE WIN!", category: 'blunder' },
  { text: "Your logic has completely failed. That move is a death sentence.", category: 'blunder' },
  { text: "An unforgivable error. You've let them win in one step.", category: 'blunder' },
  { text: "Total defensive failure. You're wide open to every threat.", category: 'blunder' },
  { text: "A blunder so bad, it might be a glitch in my system.", category: 'blunder' },
  { text: "You've handed them a winning fork that's impossible to block now.", category: 'blunder' },
  { text: "Complete tactical blindness. Look at the board properly!", category: 'blunder' },
  { text: "You've just thrown away hours of training in one move.", category: 'blunder' },
  { text: "A move so bad, it's almost impressive.", category: 'blunder' },
  { text: "You've allowed a connection that was obviously coming.", category: 'blunder' },
  { text: "Total collapse. Your pieces are working against each other.", category: 'blunder' },
  { text: "A blunder that will haunt your ELO for weeks.", category: 'blunder' },
  { text: "You've given them a walkover. Shameful display.", category: 'blunder' },
  { text: "Complete and utter logic failure. Re-calculating... error.", category: 'blunder' },
  { text: "You've missed a win so simple a 2-bit processor would find it.", category: 'blunder' },
  { text: "A blunder of historic proportions. Truly tragic.", category: 'blunder' },
  { text: "You've just opened the door and rolled out the red carpet for them.", category: 'blunder' },
  { text: "Total tactical nightmare. You're drowning out here.", category: 'blunder' },
  { text: "A blunder that shouldn't be possible at this level.", category: 'blunder' },
  { text: "You've ignored the most basic principle of the game: losing is bad.", category: 'blunder' },
  { text: "Complete strategic surrender. You've given up.", category: 'blunder' },
  { text: "A blunder so loud, even the spectators are cringing.", category: 'blunder' },
  { text: "You've effectively resigned with that move. Pathetic.", category: 'blunder' },
  { text: "Total lack of foresight. You've walked off a cliff.", category: 'blunder' },
  { text: "A blunder that invalidates everything you've learned today.", category: 'blunder' },
  { text: "You've handed them a win that they didn't even earn.", category: 'blunder' },
  { text: "Complete and utter failure of spatial reasoning.", category: 'blunder' },
  { text: "A blunder that will be used to teach what NOT to do.", category: 'blunder' },
  { text: "You've just deleted your own winning chance. Undoing is not an option.", category: 'blunder' },
  { text: "Total tactical blackout. You're playing in the dark.", category: 'blunder' },
  { text: "A blunder so egregious, it's actually offensive.", category: 'blunder' },
  { text: "You've ignored the flashing red light that said 'YOU LOSE'.", category: 'blunder' },
  { text: "Complete and total meltdown. System offline.", category: 'blunder' },
  { text: "A blunder of monumental stupidity. My apologies, I'm just being honest.", category: 'blunder' },
];

export function getCoachingComment(category: CoachingComment['category']): string {
  const filtered = COACHING_COMMENTS.filter(c => c.category === category);
  if (filtered.length === 0) return "Keep focusing on the objective.";
  return filtered[Math.floor(Math.random() * filtered.length)].text;
}
